sudo: false

language:
    - php
    - node_js

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=trunk WP_MULTISITE=0

install:
    - export DEV_LIB_PATH=dev-lib
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
    - source $DEV_LIB_PATH/travis.install.sh
    - bash bin/install-wp-tests.sh wordpress wordpress_test root '' localhost $WP_VERSION

before_script:
    - php -S localhost:8888 -t $WP_CORE_DIR  > /dev/null &

script:
    - source $DEV_LIB_PATH/travis.script.sh
    - phpunit
    - php /tmp/wp-cli.phar plugin list
    - "php /tmp/wp-cli.phar codeception run --debug"
